name: Deploy and Assign Azure Key Vault Policy

on:
  push:
    paths:
      - 'azure-scripts/**'
      - 'builtin-policy.json'
      - '.github/workflows/deploy-policy.yml'

jobs:
  deploy-and-assign-policy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Install Azure PowerShell
        run: |
          Install-Module -Name Az -Repository PSGallery -Force -Scope CurrentUser -AllowClobber
          Import-Module Az

      - name: Deploy and Assign Key Vault Policy
        shell: pwsh
        env:
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          ./azure-scripts/deploy-policy.ps1 `